export const INBOX_BATCH_SIZE = 100;
export const INBOX_MAX_RETRIES = 5;
export const INBOX_RETRY_DELAY_MS = 60_000;
export const INBOX_RECOVERY_BATCH_SIZE = 100;
export const INBOX_PROCESSING_TIMEOUT_MS = 10 * 60_000;
